# Generated by Django 5.0.6 on 2024-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P1', 'Meaty Pizza'), ('P2', 'Cheesy Pizza'), ('P3', 'Vegan Pizza'), ('P4', 'Exotic Pizza')], max_length=2),
        ),
    ]
