# Generated by Django 5.0.6 on 2024-05-27 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('boulevard', models.CharField(choices=[('MAARIF', 'MAARIF'), ('ANCIENNE MÉDINA', 'ANCIENNE MÉDINA'), ('QUARTIER DES HABOUS', 'QUARTIER DES HABOUS'), ('LA PLACE MOHAMMED-V', 'LA PLACE MOHAMMED-V'), ('DERB GHALLEF', 'DERB GHALLEF'), ('LE BOULEVARD MOHAMMED ', 'LE BOULEVARD MOHAMMED '), ('LE MARCHÉ CENTRAL', 'LE MARCHÉ CENTRAL'), ('COLLINE ANFA', 'COLLINE ANFA')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
