# Generated by Django 5.2.6 on 2025-09-10 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P1', 'Balais'), ('P2', 'Five Stars'), ('P3', 'Raclettes'), ('P4', 'Brosses'), ('P5', 'Pelles'), ('P6', 'Etagéres'), ('P7', 'Etagéres Chaussures'), ('P8', 'PASS360'), ('P9', 'RAMRAK'), ('P10', 'Cintre'), ('P12', 'Casques')], max_length=4),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
